### PR TITLE
Fix image URL and double encoded HTML entities

### PR DESCRIPTION
**Pull request by Karmalakas**
As `develop` branch is behind `master`, so creating PR to `master` - change if needed

- Fix page image URL [Issue #16](https://github.com/matt-j-m/grav-plugin-aura/issues/16)
- Fix double encoded HTML entities [Issue #12](https://github.com/matt-j-m/grav-plugin-aura/issues/12)
- Fix code style (was very inconsistent)
- Split object setting to separate methods
- Add .gitignore IDE rules

### CODE REVIEW

**Comment by Karmalakas** [comment]
> In `og:image` now the root of web project is added twice, for example:
> `https://localhost/transportopaslaugos/transportopaslaugos/user/pages/01.home/pervezimas.jpg`

@01Kuzma, how does your frontmatter of `/home` look like? Because it used to parse image based on path and now I've doe so it would take `ImageMedium` object and call `url()` method ($image->url()). But it also prepends `$this->grav['base_url_absolute']`, so I wonder what this one is  also. Could you try debugging this? I don't experience this :/

**Comment by 01Kuzma** [comment]
Hm, I've just moved a random image from desktop to Content's Page Media, then selected that image in Aura's tab.
Somehow the image path is spoiled...

```
metadata:
  'og:url': 'https://localhost/transportopaslaugos/'
  'og:image': 'https://localhost/transportopaslaugos/transportopaslaugos/user/pages/01.home/pervezimas.jpg'
```
If I delete the second path `transportopaslaugos` in Frontmatter and save, it still reloads with double path.
I've downloaded whole archive from your repo and replaced existing plugin with yours

I'm checking it on localhost. but don't think that this could be an issue :/

**Comment by Karmalakas** [comment]
Just reproduced this on test page when Grav is not in root. 

Absolute base URL and provided Image URL overlaps :/ Not sure yet how to solve it
```
^ "http://playground.local/test"
^ "/test/user/pages/01.home/logo.jpg?g-5fd44dff$"
```

Hopefully will fix this a bit later

**Comment by 01Kuzma** [comment]
I'm glad that you are able to reproduce it

**Comment by Karmalakas** [comment]
@01Kuzma, just pushed _/classes/aura.php_. Please check if it works

**Comment by 01Kuzma** [comment]
Seems working fine 👍 
I had to remove previous image and re-upload it.
Thank you!

**Comment by 01Kuzma** [comment]
Strange thing, I'm uploading a image to a home page. But in the markup looks the double '//' is added:
'og:image': 'https://website//image.png'
So, the image is not accessible

**Comment by 01Kuzma** [comment]
@matt-j-m  can you merge it?

**Pull request merged**
